#!/usr/bin/env bash
#
# Root-assisted SunsetScan validation collector.
#
# Run from the SunsetScan repo with:
#   sudo bash scripts/sudo_network_validation.sh
#
# Optional environment overrides:
#   sudo SUNSETSCAN_TARGETS="192.168.1.0/24 10.0.0.0/24" bash scripts/sudo_network_validation.sh
#   sudo SUNSETSCAN_PROFILES="PING QUICK SMB STEALTH FULL" bash scripts/sudo_network_validation.sh
#   sudo SUNSETSCAN_PASSIVE_SECONDS=60 bash scripts/sudo_network_validation.sh
#   sudo SUNSETSCAN_COMMAND_TIMEOUT=1800 bash scripts/sudo_network_validation.sh
#
# This script does not update caches, install packages, delete files, push to
# GitHub, or change network devices. It collects root-only discovery evidence
# and runs SunsetScan in safe mode against the configured local test networks.

set -uo pipefail

if [[ "${EUID}" -ne 0 ]]; then
  echo "ERROR: run this script with sudo so ARP, passive capture, SYN scan, and OS detection can be tested." >&2
  echo "Example: sudo bash scripts/sudo_network_validation.sh" >&2
  exit 1
fi

SCRIPT_DIR="$(cd -P "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
PROJECT_ROOT="$(cd -P "${SCRIPT_DIR}/.." >/dev/null 2>&1 && pwd)"
cd "${PROJECT_ROOT}" || exit 1

TS="$(date +%Y%m%d_%H%M%S)"
OUT_BASE="${SUNSETSCAN_OUT_DIR:-${PROJECT_ROOT}/reports/sudo_validation_${TS}}"
RUNNER_LOG="${OUT_BASE}/runner.log"
RUN_MARKER="${OUT_BASE}/run_started.marker"

TARGETS="${SUNSETSCAN_TARGETS:-192.168.1.0/24}"
PROFILES="${SUNSETSCAN_PROFILES:-PING QUICK SMB STEALTH FULL}"
PASSIVE_SECONDS="${SUNSETSCAN_PASSIVE_SECONDS:-45}"
SAFE_FLAG="${SUNSETSCAN_SAFE_FLAG:---safe-mode}"
COMMAND_TIMEOUT="${SUNSETSCAN_COMMAND_TIMEOUT:-1800}"

mkdir -p \
  "${OUT_BASE}/system" \
  "${OUT_BASE}/targets" \
  "${OUT_BASE}/sunsetscan" \
  "${OUT_BASE}/passive" \
  "${OUT_BASE}/html_reports"
touch "${RUN_MARKER}"

log() {
  printf '%s %s\n' "[$(date '+%Y-%m-%d %H:%M:%S')]" "$*" | tee -a "${RUNNER_LOG}"
}

have() {
  command -v "$1" >/dev/null 2>&1
}

run_cmd() {
  local label="$1"
  shift
  local logfile="${OUT_BASE}/${label}.log"
  mkdir -p "$(dirname "${logfile}")"
  log "START ${label}: $*"
  (
    printf '### command:'
    printf ' %q' "$@"
    printf '\n### timeout_seconds: %s\n### started: %s\n\n' "${COMMAND_TIMEOUT}" "$(date --iso-8601=seconds)"
    timeout --kill-after=30s "${COMMAND_TIMEOUT}" "$@"
    status=$?
    printf '\n### exit_status: %s\n### finished: %s\n' "${status}" "$(date --iso-8601=seconds)"
    exit "${status}"
  ) >"${logfile}" 2>&1
  local status=$?
  log "DONE  ${label}: exit=${status} log=${logfile}"
  return 0
}

run_shell() {
  local label="$1"
  shift
  local script="$*"
  local logfile="${OUT_BASE}/${label}.log"
  mkdir -p "$(dirname "${logfile}")"
  log "START ${label}: ${script}"
  (
    printf '### shell: %s\n### timeout_seconds: %s\n### started: %s\n\n' "${script}" "${COMMAND_TIMEOUT}" "$(date --iso-8601=seconds)"
    timeout --kill-after=30s "${COMMAND_TIMEOUT}" bash -lc "${script}"
    status=$?
    printf '\n### exit_status: %s\n### finished: %s\n' "${status}" "$(date --iso-8601=seconds)"
    exit "${status}"
  ) >"${logfile}" 2>&1
  local status=$?
  log "DONE  ${label}: exit=${status} log=${logfile}"
  return 0
}

target_id() {
  printf '%s' "$1" | tr './:' '___'
}

choose_python() {
  if [[ -x "${PROJECT_ROOT}/.venv/bin/python3" ]]; then
    printf '%s\n' "${PROJECT_ROOT}/.venv/bin/python3"
  elif [[ -x "${PROJECT_ROOT}/venv/bin/python3" ]]; then
    printf '%s\n' "${PROJECT_ROOT}/venv/bin/python3"
  else
    printf '%s\n' "python3"
  fi
}

default_iface() {
  ip route show default 2>/dev/null | awk 'NR == 1 {for (i=1;i<=NF;i++) if ($i=="dev") {print $(i+1); exit}}'
}

chown_outputs() {
  if [[ -n "${SUDO_UID:-}" && -n "${SUDO_GID:-}" ]]; then
    chown -R "${SUDO_UID}:${SUDO_GID}" "${OUT_BASE}" 2>/dev/null || true
    if [[ -f "${OUT_BASE}.tar.gz" ]]; then
      chown "${SUDO_UID}:${SUDO_GID}" "${OUT_BASE}.tar.gz" 2>/dev/null || true
    fi
    find "${PROJECT_ROOT}" -maxdepth 1 -name 'sunsetscan_assessment_*.html' -newer "${RUN_MARKER}" \
      -exec chown "${SUDO_UID}:${SUDO_GID}" {} + 2>/dev/null || true
    find "${PROJECT_ROOT}/reports" -maxdepth 1 -name 'sunsetscan_assessment_*.html' -newer "${RUN_MARKER}" \
      -exec chown "${SUDO_UID}:${SUDO_GID}" {} + 2>/dev/null || true
  fi
}

PYTHON_BIN="$(choose_python)"
IFACE="${SUNSETSCAN_IFACE:-$(default_iface)}"

log "SunsetScan sudo validation started"
log "Project root: ${PROJECT_ROOT}"
log "Output dir: ${OUT_BASE}"
log "Targets: ${TARGETS}"
log "Profiles: ${PROFILES}"
log "Python: ${PYTHON_BIN}"
log "Interface: ${IFACE:-unknown}"
log "Passive capture seconds: ${PASSIVE_SECONDS}"
log "Safe flag: ${SAFE_FLAG}"
log "Per-command timeout seconds: ${COMMAND_TIMEOUT}"

cat >"${OUT_BASE}/README_NEXT_STEPS.txt" <<EOF
This directory was generated by scripts/sudo_network_validation.sh.

It contains local network inventory evidence, SunsetScan stdout/stderr logs,
Nmap/ARP discovery output, optional passive capture, and copies of HTML
reports generated during the run.

After the run, give Codex this path:
  ${OUT_BASE}

Or the compressed archive:
  ${OUT_BASE}.tar.gz

The files can include local IPs, MAC addresses, hostnames, service banners,
and passive mDNS/SSDP/DHCP metadata.
EOF

run_cmd system/date date --iso-8601=seconds
run_cmd system/id id
run_cmd system/uname uname -a
run_cmd system/python "${PYTHON_BIN}" --version
run_cmd system/sunsetscan_version "${PYTHON_BIN}" sunsetscan.py --version
run_cmd system/cache_status "${PYTHON_BIN}" sunsetscan.py --cache-status
run_cmd system/modules "${PYTHON_BIN}" sunsetscan.py --modules

run_cmd system/ip_link ip -details -brief link
run_cmd system/ip_addr ip -details -brief addr
run_cmd system/ip_route ip route show table main
run_cmd system/ip_route_default ip route get 1.1.1.1
run_cmd system/ip_neigh ip neigh show nud all

if have ss; then
  run_cmd system/listening_sockets ss -tulpn
fi

for tool in nmap arp-scan arping fping avahi-browse tcpdump tshark nbtscan smbclient snmpwalk masscan; do
  if have "${tool}"; then
    run_shell "system/tool_${tool}" "${tool} --version || ${tool} -V || ${tool} -h || true"
  else
    log "MISSING tool: ${tool}"
  fi
done

if [[ -n "${IFACE}" && "$(have tcpdump; echo $?)" == "0" ]]; then
  PCAP="${OUT_BASE}/passive/passive_${IFACE}_${PASSIVE_SECONDS}s.pcap"
  run_shell "passive/tcpdump_${IFACE}" \
    "timeout ${PASSIVE_SECONDS}s tcpdump -ni '${IFACE}' -e -vv -s 0 -w '${PCAP}' '(arp or udp port 5353 or udp port 1900 or udp port 67 or udp port 68)'"
  if [[ -s "${PCAP}" ]]; then
    run_shell "passive/tcpdump_${IFACE}_text" \
      "tcpdump -nn -e -tttt -r '${PCAP}' > '${OUT_BASE}/passive/passive_${IFACE}_${PASSIVE_SECONDS}s.txt'"
  fi
fi

if have avahi-browse; then
  run_shell passive/avahi_browse "timeout 30s avahi-browse -art || true"
fi

if have arp-scan; then
  if [[ -n "${IFACE}" ]]; then
    run_shell passive/arp_scan_localnet "arp-scan --interface='${IFACE}' --localnet || true"
  else
    run_shell passive/arp_scan_localnet "arp-scan --localnet || true"
  fi
fi

for target in ${TARGETS}; do
  tid="$(target_id "${target}")"
  tdir="${OUT_BASE}/targets/${tid}"
  mkdir -p "${tdir}"
  log "Target block started: ${target}"

  run_shell "targets/${tid}/route_to_target" "ip route get '${target%%/*}' || true"

  if have nmap; then
    run_shell "targets/${tid}/nmap_discovery_root" \
      "nmap -sn -PR -PE -PP -PM -PA22,80,443,445 --reason -oA '${tdir}/nmap_discovery_root' '${target}'"
    run_shell "targets/${tid}/nmap_smb_root" \
      "nmap -Pn -sS -p 139,445 --open --reason -oA '${tdir}/nmap_smb_root' '${target}'"
    run_shell "targets/${tid}/nmap_top40_root" \
      "nmap -sS -sV -O --osscan-limit --top-ports 40 --reason -oA '${tdir}/nmap_top40_root' '${target}'"
  fi

  if have arp-scan; then
    if [[ -n "${IFACE}" ]]; then
      run_shell "targets/${tid}/arp_scan_target" "arp-scan --interface='${IFACE}' --retry=2 --timeout=700 '${target}' || true"
    else
      run_shell "targets/${tid}/arp_scan_target" "arp-scan --retry=2 --timeout=700 '${target}' || true"
    fi
  fi

  if have fping; then
    run_shell "targets/${tid}/fping_sweep" "fping -a -g '${target}' 2>&1 || true"
  fi

  if have nbtscan; then
    run_shell "targets/${tid}/nbtscan" "nbtscan -r '${target}' || true"
  fi

  if [[ "${SUNSETSCAN_SNMP:-0}" == "1" && "$(have nmap; echo $?)" == "0" ]]; then
    run_shell "targets/${tid}/nmap_snmp_udp" \
      "nmap -sU -p 161 --open --reason -oA '${tdir}/nmap_snmp_udp' '${target}'"
  fi

  run_cmd "sunsetscan/${tid}_instant" "${PYTHON_BIN}" sunsetscan.py --instant --target "${target}" "${SAFE_FLAG}" --no-color
  run_cmd "sunsetscan/${tid}_identify" "${PYTHON_BIN}" sunsetscan.py --identify --target "${target}" --profile QUICK "${SAFE_FLAG}" --no-color

  for profile in ${PROFILES}; do
    run_cmd "sunsetscan/${tid}_${profile}_full_assessment" \
      "${PYTHON_BIN}" sunsetscan.py --full-assessment --target "${target}" --profile "${profile}" "${SAFE_FLAG}" --no-color
  done

  log "Target block finished: ${target}"
done

log "Collecting generated HTML reports"
find "${PROJECT_ROOT}" -maxdepth 1 -name 'sunsetscan_assessment_*.html' -newer "${RUN_MARKER}" -print \
  -exec cp -p {} "${OUT_BASE}/html_reports/" \; >"${OUT_BASE}/html_reports/generated_html_files.txt" 2>&1 || true
find "${PROJECT_ROOT}/reports" -maxdepth 1 -name 'sunsetscan_assessment_*.html' -newer "${RUN_MARKER}" -print \
  -exec cp -p {} "${OUT_BASE}/html_reports/" \; >>"${OUT_BASE}/html_reports/generated_html_files.txt" 2>&1 || true

run_shell system/output_file_list "find '${OUT_BASE}' -type f -printf '%P\t%s bytes\n' | sort"

log "Creating compressed archive"
tar -czf "${OUT_BASE}.tar.gz" -C "$(dirname "${OUT_BASE}")" "$(basename "${OUT_BASE}")" 2>>"${RUNNER_LOG}" || true

chown_outputs

log "SunsetScan sudo validation finished"
log "Output dir: ${OUT_BASE}"
log "Archive: ${OUT_BASE}.tar.gz"

printf '\nDone.\nOutput dir: %s\nArchive: %s.tar.gz\n' "${OUT_BASE}" "${OUT_BASE}"
